apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java-deployment
  labels:
    app: user-java

spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-java

  template:
    metadata:
      labels:
        app: user-java

    spec:
      containers:
      - name: user-java
        image: registryczp7206.azurecr.io/user-java/poi:1.0
        ports:
        - containerPort: 80
        env:
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: oh-secret
              key: SQL_PASSWORD
        - name: SQL_USER
          valueFrom:
            configMapKeyRef:
              name: oh-configs
              key: SQL_USER
        - name: SQL_SERVER
          valueFrom:
            configMapKeyRef:
              name: oh-configs
              key: SQL_SERVER

        - name: SQL_DBNAME
          valueFrom:
            configMapKeyRef:
              name: oh-configs
              key: SQL_DB
